### ISSUE TITLE
Criação da estrutura de rotas

### ISSUE THREAD

**Issue by damasio34** [AppFriends/oluduro#1]
É necessário criar a estrutura das **rotas no angularjs**, 
para que após isso sejam criadas as demais páginas do app.

**Comment by mouradsm** [comment]
Vai criar com uiRoute ou ngRoute?

**Comment by damasio34** [comment]
Pensei no **ngRoute** mesmo, não vejo (ainda) necessidade de incluir mais um pacote no projeto... Já que o ngRoute é nativo e a princípio o que precisamos é só navegação nas rotas. 

O que acham?

**Comment by mouradsm** [comment]
Eu configurei antes de ler essa issue rs ai instalei o uiRouter rs Eu vou fazer o push com ele.. qualquer coisa se não observarmos a necessidade de utilizar os recursos que ele traz além do ngRoute eu removo e reconfiguro. tem problema?

**Comment by damasio34** [comment]
Blz, não tem problema... (y)

**Comment by mouradsm** [comment]
Vou reabrir pra poder marcar o commit blz?
